# Generated by Django 6.0.3 on 2026-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortnite_item_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('price_vbucks', models.IntegerField()),
                ('price_cop', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
                ('last_seen_in_shop', models.DateTimeField(null=True)),
            ],
        ),
    ]
