# Generated by Django 6.0.3 on 2026-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_cop',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
