# Generated by Django 6.0.3 on 2026-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price_cop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
