# Generated by Django 6.0.3 on 2026-03-20 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('friend_request_sent', 'Solicitud enviada'), ('awaiting_acceptance', 'Esperando aceptación'), ('friendship_confirmed', 'Amistad confirmada'), ('ready_to_gift', 'Listo para regalar'), ('delivered', 'Entregado'), ('failed_nickname', 'Nickname no encontrado'), ('failed_privacy', 'Privacidad bloqueada'), ('no_bot_available', 'Sin bot disponible'), ('retry_pending', 'Reintento pendiente')], default='pending_payment', max_length=30)),
                ('product_snapshot', models.JSONField()),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('epic_nickname', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_contact', models.CharField(blank=True, max_length=200)),
                ('payment_provider', models.CharField(default='mercadopago', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('friend_request_sent_at', models.DateTimeField(blank=True, null=True)),
                ('friendship_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_to_gift_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('bot_response_json', models.JSONField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
